version: '3'

services:
  frontend:
    image: 514445668943.dkr.ecr.ap-northeast-1.amazonaws.com/myapp-frontend:latest
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/myapp/frontend
    tty: true
    depends_on:
      - 'backend'

  backend:
    image: 514445668943.dkr.ecr.ap-northeast-1.amazonaws.com/myapp-backend:latest
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/myapp/backend
    environment:
      CHOKIDAR_USEPOLLING: 1
